version: '3.8'
services:
  webapp:
    image: webapp:latest
    build:
      context: .
      dockerfile: WebApp/Dockerfile
    ports:
      - "5000:8080"
    networks:
      - productcatalog
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - AppSettings__ApiBaseUrl=http://api:8080/api/v1
    depends_on:
      - api
      - migration
  
  migration:
    image: migration:latest
    build:
      context: .
      dockerfile: Api/Dockerfile
      target: migrations
    networks:
      - productcatalog
    environment:
    - ConnectionStrings__DefaultConnection=Server=db;Database=ProductCatalog;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Pooling=true;Max Pool Size=100;MultipleActiveResultSets=True;
    depends_on:
    - db

  api:
    image: api:latest
    build:
      context: .
      dockerfile: Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - productcatalog
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=ProductCatalog;User Id=sa;Password=Your_password123;TrustServerCertificate=True;Pooling=true;Max Pool Size=100;MultipleActiveResultSets=True;
      - HealthCheck__HealthCheckEndpointProtocol=http
      - HealthCheck__HealthCheckEndpointPort=8080
      - HealthCheck__ProductCatalogWebUrl=http://webapp:8080
    depends_on:
      - db
  
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - productcatalog
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
networks:
    productcatalog:
        driver: bridge